/*
 * Tinkers Construct
 * Master build file
 * 
 * Authors: Sunstrike, ProgWML6
 * Help from AbrarSyed
 */

plugins {
    id 'java'
	id 'org.gradlex.reproducible-builds' version '1.1'
    id 'net.minecraftforge.gradle' version '7.0.40'
    id 'net.minecraftforge.renamer' version '1.1.7'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

tasks.withType(JavaCompile).configureEach {
    options.fork = true
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-source', '1.6', '-target', '1.6']
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    maven {
        name 'CB'
        url "https://maven.covers1624.net"
    }
    maven {
        name = 'Curse Maven'
        url = 'https://www.cursemaven.com'
    }
}

group = 'tconstruct'

ext.artifact_version_override = 'NotUsed'

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    compileOnly renamer.dependency("curse.maven:ForgeMultipart-229323:2233279")
    compileOnly "codechicken:NotEnoughItems:${minecraft_version}-${NEI_version}:dev"
    compileOnly files("libs/CodeChickenLib-dev-${minecraft_version}-${CCLIB_version}.jar")
}

renamer.mappings.from minecraft.dependency.toObfFile

// Finds and sets version data
task buildInfo {
    def cmd = "git rev-parse --short HEAD"
    def proc = cmd.execute()
    proc.waitFor()
    if (proc.exitValue() == 0) {
        ext.revision = proc.text.trim()
    } else {
        ext.revision = "GITBORK"
    }

    if (System.getenv().BUILD_NUMBER != null) {
        ext.buildNum = System.getenv().BUILD_NUMBER
    } else {
        ext.buildNum = "DEV"
    }
}
ext.artifact_version = 'NFG'
if (System.getenv().ARTIFACT_VERSION == null && artifact_version_override == 'NotUsed') {
    artifact_version = "${project.buildInfo.buildNum}.${project.buildInfo.revision}"
}
if (System.getenv().ARTIFACT_VERSION != null && artifact_version_override == 'NotUsed') {
    artifact_version = "${system.getenv().ARTIFACT_VERSION}"
}
if (artifact_version_override != 'NotUsed') {
    artifact_version = "${artifact_version_override}"
}
version = "${minecraft_version}-${artifact_version}"

minecraft {
    mappings channel: 'snapshot', version: '20130918-1.6.3'
    accessTransformer.from file('resources/META-INF/accesstransformer.cfg')
    // replace '${version}', project.version

    runs {
        register('client') {
            workingDir = file('runs/main/client/')
            environment.put('tweakClass', 'cpw.mods.fml.common.launcher.FMLTweaker')
            jvmArgs '-Dfml.ignoreInvalidMinecraftCertificates=true'
        }
        register('server') {
            workingDir = file('runs/main/server/')
            environment.put('tweakClass', 'cpw.mods.fml.common.launcher.FMLServerTweaker')
            jvmArgs '-Dfml.ignoreInvalidMinecraftCertificates=true'
        }
    }
}


sourceSets {
    main {
        java.srcDirs = ['src/main/java', 'src/api/java']
		resources.srcDirs = ['resources']
    }
}
sourceSets.main.output.resourcesDir = sourceSets.main.output.classesDirs.singleFile

processResources {
    filesMatching('**/*.info') {
        filter { line ->
            line.replace('@VERSION@', artifact_version).replace('@MCVERSION@', minecraft_version)
        }
    }
}

// Add Coremod Manifest
jar {
    manifest {
        attributes 'FMLCorePlugin': 'tconstruct.preloader.TConstructLoaderContainer'
        attributes 'FMLCorePluginContainsFMLMod': 'true'
    }
}

// Create deobf dev jars
task deobfJar(type: Jar) {
    from sourceSets.main.output
    archiveClassifier = 'deobf'
}

// Create API library jar
task libJar(type: Jar) {
    from(sourceSets.main.java) {
        include "tconstruct/library/*"
    }
    archiveClassifier = 'lib'
}

artifacts {
    archives deobfJar
    archives libJar
}

task("uploadJars", dependsOn:"build") {
    
    description = "uploads JARs"

    if (project.hasProperty("local_maven")) {
	    apply plugin: 'maven'
            uploadArchives {
                repositories {
                    mavenDeployer {
                        repository(url: "file://${local_maven}")
                }
            }
        }
    }
}
