/*
 * Tinkers Construct
 * Master build file
 * 
 * Authors: Sunstrike, ProgWML6
 * Help from AbrarSyed
 */

plugins {
    id 'java'
	id 'org.gradlex.reproducible-builds' version '1.1'
	id 'pl.allegro.tech.build.axion-release' version '1.21.2'
	id 'com.diffplug.spotless' version '8.10.3'
    id 'net.minecraftforge.gradle' version '7.0.40'
    id 'net.minecraftforge.renamer' version '1.1.7'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

tasks.withType(JavaCompile).configureEach {
    options.fork = true
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-source', '1.6', '-target', '1.6']
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    maven {
        name = 'CB'
        url = "https://maven.covers1624.net"
    }
    maven {
        name = 'Curse Maven'
        url = 'https://www.cursemaven.com'
    }
}

group = 'tconstruct'

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    compileOnly renamer.dependency("curse.maven:ForgeMultipart-229323:2233279")
    compileOnly "codechicken:NotEnoughItems:${minecraft_version}-${NEI_version}:dev"
    compileOnly files("libs/CodeChickenLib-dev-${minecraft_version}-${CCLIB_version}.jar")
}

renamer.mappings.from minecraft.dependency.toObfFile

renamer.classes(tasks.named('jar', Jar)) {
    map.from minecraft.dependency.toSrgFile
    archiveClassifier = 'srg'
}

renamer.classes('renameJarToSrg', tasks.named('jar', Jar)) {
    mappings(minecraft.dependency.toSrg.get())
    archiveClassifier = ""
}

tasks.withType(JavaCompile) {
    options.compilerArgs << '-Xlint:unchecked'
    options.deprecation = true
}

// FIXME: this should work?
// def artifact_version = scmVersion.version
def artifact_version = "2026.09.29"
version = "${minecraft_version}-${artifact_version}"

minecraft {
    mappings channel: 'snapshot', version: '20130918-1.6.3'
    accessTransformer.from file('resources/META-INF/accesstransformer.cfg')

    runs {
        register('client') {
            workingDir = file('runs/main/client/')
            environment.put('tweakClass', 'cpw.mods.fml.common.launcher.FMLTweaker')
            jvmArgs '-Dfml.ignoreInvalidMinecraftCertificates=true'
        }
        register('server') {
            workingDir = file('runs/main/server/')
            environment.put('tweakClass', 'cpw.mods.fml.common.launcher.FMLServerTweaker')
            jvmArgs '-Dfml.ignoreInvalidMinecraftCertificates=true'
        }
    }
}

spotless {
  java {
    targetExclude("src/api/java/**.java") // third-party code
    removeUnusedImports('cleanthat-javaparser-unnecessaryimport')
    cleanthat()
    googleJavaFormat().formatJavadoc(false)
    formatAnnotations()
  }
  json {
    target 'src/**/*.info'
    simple()
  }
}

sourceSets {
    main {
        java.srcDirs = ['src/main/java', 'src/api/java']
		resources.srcDirs = ['resources']
    }
}
sourceSets.main.output.resourcesDir = sourceSets.main.output.classesDirs.singleFile

processResources {
    filesMatching('**/*.info') {
        filter { line ->
            line.replace('@VERSION@', artifact_version).replace('@MCVERSION@', minecraft_version)
        }
    }
}

// Add Coremod Manifest
jar {
    archiveClassifier = "dev"
    manifest {
        attributes 'FMLCorePlugin': 'tconstruct.preloader.TConstructLoaderContainer'
        attributes 'FMLCorePluginContainsFMLMod': 'true'
    }
}
